### ISSUE TITLE
Add information about the current draw to each of the modules pages.

### ISSUE THREAD

**Issue by rl2939** [QuinnFreedman/modular#47]
It would be good to list how much current each module draws on the +12 volt, the -12 volt, and the 5 volt rails.
This would be useful information for those who DIY their power supply.

**Comment by QuinnFreedman** [comment]
This is on my list to do. I just recently got the equipment to be able to measure this. I should be able to add these in the next month.

For now, you can assume the current draw is pretty low on all of them. There is no particular analog circuit that would burn a lot of power, so I'd guess they are all probably under 50mA. A large portion of that is going to be on the 5v rail for the digital modules.

**Comment by QuinnFreedman** [comment]
It looks like my new power supply can't actually measure this on all 3 channels. I'll buy an actual ammeter. For now it looks like everything is in the 10mA or less neighborhood per rail except for Output which is ~40mA on both rails.

**Comment by roagm** [comment]
I have measured the current draw for the modules that I have built. Here is the information in case you find it useful.

**Offset/Atten**
- 12V: 6 mA
- -12V: 6mA
- 5V: N/A

**Clock**
- 12V: N/A
- -12V: N/A
- 5V:
  - 30mA typical
  - 45 mA max (idle, all-white screen)

**Envelope**

- 12V: N/A
- -12V: 1 mA
- 5V 21mA

**Drift**

- 12V: 5 mA
- -12V: 5 mA
- 5V: 25 mA

**Comment by roagm** [comment]
**RNG**

- 12V: 5mA
- -12V: 5mA
- 5V: Bias knob seems to affect current draw the most. Probably because it affects how many LEDs in the row of 7 light up
  - 22 mA with Bias knob all the way CCW (all row off)
  - 40 mA with Bias knob all the way CW (all row on)
