### ISSUE TITLE
(Request) Add A Semimodular System

### ISSUE THREAD

**Issue by rl2939** [QuinnFreedman/modular#49]
Considering that this project attempts to make synthesis accessible to everyone, a semimodular system would be great for those who are new to modular synthesis but don't really know exactly what they want out of a system. It would also cover a lot of bases for those that also want to get started with an "all-in-one" device.

An example of a semimodular system could include:
- A sound source
- A way to shape that sound source (like a filter or wavefolder)
- A VCA
- An Envelope generator
- Some way to play or sequence the system

**Comment by QuinnFreedman** [comment]
I'm not opposed to this, but I think this will be a while down the road. I have my next year or so of development filled with ideas for individual modules. Once I have designed each of these parts individually, I would look into combining them into a semimodular.

I'm closing this for now to keep my issues organized, but I appreciate the input
